
server {
    listen 443 ssl;
    server_name adminer.cwoon.42.my;

    ssl_protocols TLSv1.2 TLSv1.3;
	ssl_certificate /run/secrets/ssl_cert;
	ssl_certificate_key /run/secrets/ssl_key;

	# $remote_addr: This is the real IP address of the person visiting your site.
    location / {
        # We proxy to the internal Adminer port
        proxy_pass http://adminer:8080;

        # Essential headers for the Adminer GUI to know who is talking to it
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}