# Server block for the static portfolio
server {
    listen 443 ssl;
    server_name portfolio.cwoon.42.my; # e.g., portfolio.cwoon.42.my

    ssl_protocols TLSv1.2 TLSv1.3;
	ssl_certificate /run/secrets/ssl_cert;
	ssl_certificate_key /run/secrets/ssl_key;

    root /var/www/portfolio;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}