
server {
    listen 443 ssl;
    server_name kuma.cwoon.42.my;

    ssl_protocols TLSv1.2 TLSv1.3;
	ssl_certificate /run/secrets/ssl_cert;
	ssl_certificate_key /run/secrets/ssl_key;

	location / {
    proxy_pass http://uptime-kuma:3001/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
	}

	location ~ ^/(assets|api|socket.io|setup-database|dashboard|metrics) {
    proxy_pass http://uptime-kuma:3001;
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
}