server {
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name cwoon.42.my;

	ssl_certificate /etc/nginx/ssl/inception.crt;
	ssl_certificate_key /etc/nginx/ssl/inception.key;

	ssl_protocols TLSv1.3;

	root /var/www/html;
	index index.php index.html;

	location / {
		try_files $uri $uri/ =404;
	}

	location ~ \.php {
		fastcgi_pass wordpress-test:9000;
		fastcgi_index index.php;

		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}

	# $remote_addr: This is the real IP address of the person visiting your site.
	# The trailing slashes here are CRITICAL
	# This fixes the exact redirect loop you see in your screenshot
	# It tells NGINX to rewrite 'Location: index.php' to 'Location: /adminer/index.php'
	location /adminer/ {
		proxy_pass http://adminer-test:8080/;
		proxy_set_header Host $host;
		# proxy_set_header X-Real-IP $remote_addr;
		# proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		# proxy_set_header X-Forwarded-Proto $scheme;
		proxy_redirect /index.php /adminer/index.php;
	}

	# Optional: Redirect non-slash to slash version
	# $host: This is the domain name the user typed in their browser (e.g., cwoon.42.my).
	# $scheme: This is the protocol being used (http or https).
	location = /adminer {
		return 301 $scheme://$host/adminer/;
	}
}

# Server block for the static portfolio
server {
    listen 443 ssl;
    server_name portfolio.cwoon.42.my; # e.g., portfolio.cwoon.42.my

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    root /var/www/portfolio;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}