server {
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name cwoon.42.my;

	ssl_certificate /run/secrets/ssl_cert;
	ssl_certificate_key /run/secrets/ssl_key;

	ssl_protocols TLSv1.2 TLSv1.3;

	root /var/www/html;
	index index.php index.html;

	location / {
		try_files $uri $uri/ =404;
	}

	# ~ case-sensitive regex match, anything that ends in .php (\ is just an escape character)
	# fastcgi wrapper for incoming HTTP requests (Protocol translation)
	# include fastcgi_params is a template that allows variable mapping to convert HTTP request > FastCGI packet
	# $document_root = /var/www/html
	# $fastcgi_script_name = index.php
	# These HTTP details are mapped into FastCGI Environment Variables. For example:
		# The URL index.php becomes SCRIPT_FILENAME.
		# The HTTP GET method becomes REQUEST_METHOD.
	location ~ \.php {
		fastcgi_pass wordpress:9000;
		fastcgi_index index.php;

		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}

}
