services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - PENULTIMATE_DEBIAN_STABLE_VERSION=${PENULTIMATE_DEBIAN_STABLE_VERSION}
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql:rw
    networks:
      - inception
    secrets:
      - db_credentials
      - db_password
      - db_root_password
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - PENULTIMATE_DEBIAN_STABLE_VERSION=${PENULTIMATE_DEBIAN_STABLE_VERSION}
        - PHP_VERSION=${PHP_VERSION}
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html:rw
    networks:
      - inception
    secrets:
      - db_credentials
      - db_password
      - db_root_password
      - wp_admin_credentials
      - wp_admin_password
      - wp_user_credentials
      - wp_user_password
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        - PENULTIMATE_ALPINE_STABLE_VERSION=${PENULTIMATE_ALPINE_STABLE_VERSION}
    container_name: nginx
    depends_on:
    - wordpress
    ports:
      - "443:443"
      # - "80:80"
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception
    secrets:
      - ssl_key
      - ssl_cert
    restart: always

  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
      args:
        - PENULTIMATE_ALPINE_STABLE_VERSION=${PENULTIMATE_ALPINE_STABLE_VERSION}
    container_name: adminer
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
      args:
        - PENULTIMATE_DEBIAN_STABLE_VERSION=${PENULTIMATE_DEBIAN_STABLE_VERSION}
    container_name: redis
    networks:
      - inception
    restart: always

  ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
      args:
        - PENULTIMATE_ALPINE_STABLE_VERSION=${PENULTIMATE_ALPINE_STABLE_VERSION}
    container_name: ftp
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html:rw
    networks:
      - inception
    secrets:
      - ftp_password
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    restart: always

  cadvisor:
    build:
      context: ./requirements/bonus/cadvisor
      dockerfile: Dockerfile
      args:
        - PENULTIMATE_DEBIAN_STABLE_VERSION=${PENULTIMATE_DEBIAN_STABLE_VERSION}
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - inception
    restart: always

  uptime_kuma:
    build:
      context: ./requirements/bonus/uptime-kuma
      dockerfile: Dockerfile
      args:
        - PENULTIMATE_DEBIAN_STABLE_VERSION=${PENULTIMATE_DEBIAN_STABLE_VERSION}
    container_name: uptime-kuma
    volumes:
      - uptime-kuma_data:/app/data
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_MOUNT_PATH}/mariadb
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_MOUNT_PATH}/wordpress
  uptime-kuma_data:
    name: uptime-kuma_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_MOUNT_PATH}/uptime-kuma

networks:
  inception:
    driver: bridge
    name: inception

secrets:
  db_credentials:
    name: db_credentials
    file: ../secrets/db_credentials.txt
  db_password:
    name: db_password
    file: ../secrets/db_password.txt
  db_root_password:
    name: db_root_password
    file: ../secrets/db_root_password.txt
  ssl_key:
    name: ssl_key
    file: ../secrets/inception.key
  ssl_cert:
    name: ssl_cert
    file: ../secrets/inception.crt
  wp_admin_credentials:
    name: wp_admin_credentials
    file: ../secrets/wp_admin_credentials.txt
  wp_admin_password:
    name: wp_admin_password
    file: ../secrets/wp_admin_password.txt
  wp_user_credentials:
    name: wp_user_credentials
    file: ../secrets/wp_user_credentials.txt
  wp_user_password:
    name: wp_user_password
    file: ../secrets/wp_user_password.txt
  ftp_password:
    name: ftp_password
    file: ../secrets/ftp_password.txt
