# Disables random guests, but allows created users, allow it STOR(upload), DELE(delete), RNFR(rename) command options, these are specific to the FTP protocol
anonymous_enable=NO
local_enable=YES
write_enable=YES

# Jail the logged in user in the working directory, but at the same time give them write access to upload files
chroot_local_user=YES
allow_writeable_chroot=YES
secure_chroot_dir=/var/run/vsftpd/empty

# About Linux Kernel Security
# Disabled as this interferes with Docker container security defaults
seccomp_sandbox=NO

# Passive Mode Config
# Passive - waits for client to connect
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110

# VM IP
pasv_address=10.0.2.15 # Or localhost if you want to just do it in the VM terminal